### ISSUE TITLE
Update project.json to use new v4.3.0 of StructureMap

### ISSUE THREAD

**Issue by rguerreiro** [structuremap/StructureMap.Microsoft.DependencyInjection#13]
New StructureMap's version fixes the issue reported here: https://github.com/structuremap/structuremap.dnx/issues/6#issuecomment-234788669

**Comment by khellang** [comment]
This project has now been renamed to StructureMap.Microsoft.DependencyInjection. I've pushed a new package with an updated dependency on SM v4.3.0 [here](https://www.nuget.org/packages/structuremap.microsoft.dependencyinjection) :smile:

**Comment by no1melman** [comment]
I've tried this new package out, I get the restore complaining it can't find `StructureMap  >= 4.3.0`

```json
{
  "dependencies": {
    "MediatR": "2.1.0",
    "MediatR.Extensions.Microsoft.DependencyInjection": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.EntityFrameworkCore": "1.0.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },
    "StructureMap": "4.3.0",
    "StructureMap.Microsoft.DependencyInjection": "1.0.0"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

Is this my fault?

**Comment by khellang** [comment]
Not sure what's wrong. Can you try the package id all lowercase? I think the original package id is `structuremap`. The package is definitely there; https://www.nuget.org/packages/structuremap/4.3.0

**Comment by no1melman** [comment]
Yeah, that worked.... fecking id's, why is that case sensitive....

**Comment by khellang** [comment]
Yeah, NuGet is pretty weird about casing. There's also the confusion between "title" and "id". Anyway, you can just remove the explicit SM dependency now, since SM.MS.DI will bring it in, transitively.

**Comment by rguerreiro** [comment]
Thank for the quick solution.

Just as a sidenote I also needed to add the package in lowercase: `"structuremap.microsoft.dependencyinjection": "1.0.0"`
