### ISSUE TITLE
ViewComponentContext.ViewContext.HttpContext.RequestServices is sometimes null

### ISSUE THREAD

**Issue by asweeney76** [structuremap/StructureMap.Microsoft.DependencyInjection#15]
I have the following two controller actions:

```
public async Task<IActionResult> FacilityDetails()
{
    return await Task.FromResult(ViewComponent("FacilityDetails"));
}

public async Task<IActionResult> RecentInvoices()
{
    return await Task.FromResult(ViewComponent("RecentInvoices"));
}
```

And the following two ajax requests that are called at the same time:

```
function GetFacilityDetails() {
    $.get("/FacilityDashboard/FacilityDetails", function (data) {
        $('#facility-dashboard-facility-details').html(data);
    });
}

function GetRecentInvoices() {
    $.get("/FacilityDashboard/RecentInvoices", function (data) {
        $('#facility-dashboard-recent-invoices').html(data);
    });
}
```

After a little digging, I'm finding that ViewComponentContext.ViewContext.HttpContext.RequestServices is null by the time the second ViewComponent is being rendered - but only occasionally. Very odd behavior. I thought that each request would get its own scoped container on the HttpContext ( from the following middleware )

```
public async Task Invoke(HttpContext httpContext)
{
    using (var container = RequestServicesContainer.EnsureRequestServices(httpContext, _services))
    {
        await _next.Invoke(httpContext);
    }
}
```

Any suggestions would be much appreciated

**Comment by khellang** [comment]
What is `RequestServicesContainer` and what is `EnsureRequestServices` doing? The StructureMap adapter doesn't have anything to do with setting the request services on the `HttpContext`. That's something the ASP.NET Core hosting layer takes care of.

**Comment by khellang** [comment]
Since this issue's been inactive for so long, I'm closing it. Please feel free to reopen if there still is unresolved issues.
