### ISSUE TITLE
Scanning for assemblies not working with NETCOREAPP1_0

### ISSUE THREAD

**Issue by malclear** [structuremap/StructureMap.Microsoft.DependencyInjection#18]
An issue with StructureMap not being able to scan for assemblies when using NETCoreApp has been corrected. This library should advance its StructureMap version reference to >= 4.4.2.
Refer to issues 522 and 523: https://github.com/structuremap/structuremap/pull/523

**Comment by khellang** [comment]
This will probably happen with the next release. In the meantime, you can just pin the version in your project :smile:

**Comment by khellang** [comment]
I've pushed a new version, [v1.3.0](https://www.nuget.org/packages/StructureMap.Microsoft.DependencyInjection/1.3.0) that has bumped the dependency on SM to 4.4.2 :smile:
