### ISSUE TITLE
ConfigureContainer(Registry registry) not called

### ISSUE THREAD

**Issue by CMircea** [structuremap/StructureMap.Microsoft.DependencyInjection#22]
The README says that after calling `app.UseStructureMap()` the runtime will look for a `ConfigureContainer` method, however, there isn't any code that actually does this, so the `StructureMap.AspNetCore` package is kinda useless on its own.

**Comment by khellang** [comment]
What are you talking about?

> The package adds the `UseStructureMap` extension method to `IWebHostBuilder`.

There's no mentioning of `app` anywhere.

The code that makes the hosting layer call `Startup.ConfigureContainer` [is here](https://github.com/structuremap/StructureMap.Microsoft.DependencyInjection/blob/master/src/StructureMap.Microsoft.DependencyInjection/ServiceCollectionExtensions.cs#L14).

**Comment by CMircea** [comment]
Hmm... my bad. I don't get ConfigureContainer called on ASP.NET Core 1.0.1. Digging further into this, support for it was added in ASP.NET Core 1.1.

Here is `StartupLoader` for 1.0.1: https://github.com/aspnet/Hosting/blob/rel/1.0.1/src/Microsoft.AspNetCore.Hosting/Internal/StartupLoader.cs

And here is `StartupLoader` for 1.1: https://github.com/aspnet/Hosting/blob/rel/1.1.0/src/Microsoft.AspNetCore.Hosting/Internal/StartupLoader.cs

For 1.1 we can see on line 18 that it does look for a ConfigureContainer method, while 1.0.1 doesn't have that functionality. The StructureMap.AspNetCore package is useful only for 1.1, but this isn't mentioned anywhere. I checked and even the version isn't suggestive - it's 1.0.0, it should be the same as ASP.NET Core's version IMO (1.1). I have now seen the dependency on `Microsoft.AspNetCore.Hosting.Abstractions` version 1.1, but that is quite easy to miss.

I suggest documenting that StructureMap.AspNetCore only supports ASP.NET Core 1.1. It works with 1.0 only if you use the overload that takes a `Registry`, which isn't as useful :)

Sorry for jumping to the conclusion that the package is useful, that was my mistake and I was too harsh.

**Comment by khellang** [comment]
Sure, I'll clarify this in the documentation.

> It works with 1.0 only if you use the overload that takes a `Registry`, which isn't as useful

What does that mean?

**Comment by CMircea** [comment]
It means that in 1.0 you can create the container in any way you fancy and call this overload of `AddStructureMap`: https://github.com/structuremap/StructureMap.Microsoft.DependencyInjection/blob/master/src/StructureMap.Microsoft.DependencyInjection/ServiceCollectionExtensions.cs#L12

There's no automatic support for `ConfigureContainer`, so you have to do the equivalent yourself, and there's two ways to integrate StructureMap:

1. Use the `IServiceProvider ConfigureServices(IServiceCollection services)` method, and manually return `new StructureMapServiceProvider(Container)`
2. Call `AddStructureMap(Registry)` in `Configure(IApplicationBuilder app)`.

I prefer the first option, as I can manually call `Populate(services)` and then `AssertConfigurationIsValid`.

**Comment by khellang** [comment]
I'm not sure what you're saying. In 1.1, [which the library *requires*](https://github.com/structuremap/StructureMap.Microsoft.DependencyInjection/blob/master/src/StructureMap.Microsoft.DependencyInjection/project.json#L26), you can, as you say, call either `IWebHostBuilder.UseStructureMap`, or `IServiceCollection.AddStructureMap`. These are equivalent. They will both call `ConfigureContainer(Registry)`. There should be no way to use this in a 1.0 app. I'm not sure what you mean by "call `AddStructureMap(Registry) in `Configure(IApplicationBuilder)`. By the time `Configure(IApplicationBuilder)` is called, it's too late to call anything on the service collection. Where do you even get a service collection in that method?

**Comment by CMircea** [comment]
My bad, I mixed up `IApplicationBuilder` with `IWebHostBuilder`, I meant calling `IWebHostBuilder.UseStructureMap`.

> There should be no way to use this in a 1.0 app.

Sure there is. Add it as a dependency, you will get `Microsoft.Extensions.DependencyInjection.Abstractions` version 1.1 but all other packages will be 1.0. DependencyInjection 1.1 is backwards compatible to ASP.NET Core 1.0 from what I can tell. IIRC the [ASP.NET team tested StructureMap against 1.0](https://github.com/aspnet/DependencyInjection/issues/433#issuecomment-243360317) and only the constructor selection was a problem.

**Comment by khellang** [comment]
Oh, I see what you're saying now. You get 1.1 of the DI-specific packages, but the hosting layer won't know what to do with the `IServiceProviderFactory<T>` service. That's exactly right. It's a good point that this should be mentioned in the README.

**Comment by CMircea** [comment]
Yeah, that's exactly right.

Compatibility with 1.0 should be documented, but mentioned that the `StructureMap.AspNetCore` package requires ASP.NET Core 1.1 :).
