### ISSUE TITLE
Is there any particular reason the Populate method takes a Registry and not an IRegistry?

### ISSUE THREAD

**Issue by Pvlerick** [structuremap/StructureMap.Microsoft.DependencyInjection#26]
Currenty signature is
```csharp
public static void Populate(this Registry registry, IEnumerable<ServiceDescriptor> descriptors)
```

Shouldn't it be on ```IRegistry``` instead
```csharp
public static void Populate(this IRegistry registry, IEnumerable<ServiceDescriptor> descriptors)
```

Just wondering :-)

**Comment by khellang** [comment]
Yes, there are reasons; the `IRegistry` interface does not allow you to set policies etc. Just try changing the signature and see what breaks :wink:

**Comment by Pvlerick** [comment]
I did, it builds fine and the test is still passing :-)

It also seems that ```public static void Populate(this ConfigurationExpression config, IEnumerable<ServiceDescriptor> descriptors)``` is not useful either, since ```ConfigurationExpression``` inherits from ```Registry``` (and hence indirectly implements ```IRegistry```)

Or am I missing something obvious?

We stumbled upon the issue while using that: https://github.com/davidfowl/ServiceProviderFactorySample/blob/master/src/ServiceProviderFactorySample/Extensions/StructureMapExtensions.cs, which was adapter to use IRegistry/Registry. But this is all useless now because of this project ;-)

**Comment by khellang** [comment]
The reason the `ConfigurationExpression` overload exists is because that was the initial method. The `Registry` overload was introduced later, but we didn't want to break people. I guess we could move everything to `IRegistry` and do a major version bump.

**Comment by Pvlerick** [comment]
Yes, I was going to say that this would be a (binary) breaking change.

I'll do a small PR that you can include when you'll feel like making a new major version :-)

Thanks!
