### ISSUE TITLE
Services configured by webhost default builder missing

### ISSUE THREAD

**Issue by arishlabroo** [structuremap/StructureMap.Microsoft.DependencyInjection#32]
In aspnet core 2 app, default webhost builder configures logging. If we add StructureMap container, the existing loggers get removed.

Reproduction:
https://github.com/arishlabroo/LoggingIssue/blob/master/WebApplication1/Program.cs

What am I doing wrong?

also see 
https://github.com/aspnet/MetaPackages/issues/201.
To double check, tested with Autofac, and it works as expected.

**Comment by khellang** [comment]
@davidfowl Anything changed here between 1.1 and 2.0? Why would this change?

**Comment by arishlabroo** [comment]
Hey @khellang , did you get a chance to look at this issue? I was trying to dig some but didn't get very far. 

Both `ILogger{T}` and `ILoggerFactory` servicedescriptors are forwared to the structuremap registry correctly, but the logger configuration set up here 
https://github.com/aspnet/MetaPackages/blob/396f413b389f5983e413be465f917cbfdbda26c9/src/Microsoft.AspNetCore/WebHost.cs#L180-L185
does not persist.

**Comment by davidfowl** [comment]
How does it fail?

**Comment by arishlabroo** [comment]
@davidfowl, It drops the debug and console loggers added by the default webhostbuilder

**Without** structuremap there are **two** loggers
 
![image](https://user-images.githubusercontent.com/771111/29594858-b88a287a-8768-11e7-958e-8375bd72e80d.png)

**With** structuremap, **0**

![image](https://user-images.githubusercontent.com/771111/29594868-c85d3e5e-8768-11e7-864e-a9ba2ee28adc.png)

**Comment by arishlabroo** [comment]
Hey @khellang 😱 2.0 Logging doesn't work with structuremap container at all. I incorrectly assumed it had something to do with the new webhost default builder. 
https://github.com/arishlabroo/LoggingIssue/blob/master/MinimalTest/LoggingStructureMapTests.cs#L40
The minimal test shows a structuremap container populated with a `ServiceCollection` drops loggers.
😢 😢 
Please tell me I am doing something wrong or, there is a workaround. Logging is indispensable and right now I cant use structuremap in my 2.0 app

**Comment by khellang** [comment]
> The minimal test shows a structuremap container populated with a `ServiceCollection` drops loggers.

Why would it drop loggers? All `UseLogging` does is register `ILogger<>` as an open generic type:

https://github.com/aspnet/Logging/blob/c821494678a30c323174bea8056f43b93a3ca6f4/src/Microsoft.Extensions.Logging/LoggingServiceCollectionExtensions.cs#L42

I thought it could be something wrong with open generics, but I tried running this test, and it passes with flying colors:

```csharp
[Fact]
public void CanResolveOpenGenericTypes()
{
    var services = new ServiceCollection
    {
        ServiceDescriptor.Singleton(typeof(ILogger<>), typeof(Logger<>))
    };

    var container = new Container();

    container.Populate(services);

    var result = container.GetInstance<ILogger<string>>();

    Assert.NotNull(result);
}

private interface ILogger<T> { }

private class Logger<T> : ILogger<T> { }
```

Also, it would be weird if the specification tests didn't already include a test for this.

**Comment by khellang** [comment]
OK, I think I've found the problem. This anti-pattern right here;

https://github.com/aspnet/Logging/blob/3a4271f3a2792418d87d289ca8b5c43e7759b1cb/src/Microsoft.Extensions.Logging/LoggerFactory.cs#L23-L40

StructureMap probably fails miserably when trying to figure out which of those constructors to use.

@pakrym @davidfowl Why do DI-services like this have tons of constructors? It makes it much harder than it needs to be for adapters to fall in line with the default behavior.

**Comment by khellang** [comment]
@arishlabroo You could try working around the problem by adding a class like this

```csharp
public class BrokenLoggerFactoryFixer : ILoggerFactory
{
    public BrokenLoggerFactoryFixer(IEnumerable<ILoggerProvider> providers, IOptionsMonitor<LoggerFilterOptions> options)
    {
        Inner = new LoggerFactory(providers, options);
    }

    private ILoggerFactory Inner { get; }

    public void Dispose() => Inner.Dispose();

    public ILogger CreateLogger(string categoryName) => Inner.CreateLogger(categoryName);

    public void AddProvider(ILoggerProvider provider) => Inner.AddProvider(provider);
}
```

And then adding that class to the service collection *before* calling `UseLogging`:

```csharp
services.AddSingleton<ILoggerFactory, BrokenLoggerFactoryFixer>();
services.AddLogging(x => x.AddConsole());
```

This should force StructureMap to use the correct constructor and hopefully fix the problem.

I'll see if we can tweak the constructor selection even more to avoid default constructors if present...

**Comment by pakrym** [comment]
@khellang this class is sometimes consumed without DI, so we provider overloads for convenience. I don't think issue is the amount of overloads we have as long as we don't rely on internal behaviors of Microsoft DI.

**Comment by khellang** [comment]
@arishlabroo I've pushed a new version, v1.4.0, to NuGet. Can you check it out and let me know if it fixes the bug?

**Comment by arishlabroo** [comment]
Wow, thanks for the amazingly quick turnaround @khellang . In my quick test project it works now.... YAYEE ... 🎆  Will let you know if I see anything else.

THANK YOU.

**Comment by rustybox** [comment]
I'm impacted by this issue with 1.4.0  just switched over from AutoFac and now I can't resolve ILogger<T>, any advice would be much appreciated.

**Comment by rustybox** [comment]
@khellang I attempted to setup a repro repo but it works just fine there so it's something specific to my other project.

Apologies, apparently this is indeed working as one would expect.

**Comment by khellang** [comment]
No problem. Feel free to open another issue if you think there's anything I can do to clear things up 😊

**Comment by rrangaiya** [comment]
@khellang I'm getting the same issue with the Application Insights logger provider. 

Trace logs are not pushed to App Insights when using the StructureMap container however it works with the default DI container. The Console logger works in both cases. I'm on version 2.0

I'm guessing it's something to do the constructor resolution for the ApplicationInsightsLoggerProvider however I'm not getting any StructureMap exceptions

This is my builder configuration, am I missing something?

                    var builder = new HostBuilder();
			
			builder.ConfigureWebJobs(b =>
			{
				b.AddAzureStorageCoreServices();
				b.AddAzureStorage();				
			});			
			
			builder.ConfigureLogging((context, b) =>
			{
				b.SetMinimumLevel(LogLevel.Trace);

				// Add logging providers.
				b.AddConsole();
                            
                            string appInsightsKey = ConfigurationManager.AppSettings["APPINSIGHTS_INSTRUMENTATIONKEY"];				
			        if (!string.IsNullOrEmpty(appInsightsKey))
				{                    
                                  b.AddApplicationInsightsWebJobs(o => o.InstrumentationKey = appInsightsKey);
				}
			});

			//Configure IoC to use StructureMap
			builder.ConfigureServices(ConfigureServices)
			       .UseServiceProviderFactory(new StructureMapServiceProviderFactory(null))
			       .ConfigureContainer<Registry>(ConfigureContainer);
