### ISSUE TITLE
Was updating Microsoft.Extensions.DependencyInjection.Abstractions?

### ISSUE THREAD

**Issue by dazinator** [structuremap/StructureMap.Microsoft.DependencyInjection#33]
As of version > 1.2.1, I noticed the constraint for the dependency of `Microsoft.Extensions.DependencyInjection.Abstractions` went from >= `1.0.0` to >= `1.1.0`. Was there a reason for this? If there wasn't, would you consider relaxing this again?

**Comment by khellang** [comment]
> Was there a reason for this?

Yes, the reason was to use the new `IServiceProviderFactory` functionality, so you could do `UseStructureMap` on your `WebHostBuilder` and the hosting layer would call the `ConfigureContainer` method on your `Startup` class. I'm not sure we would change this back I'm afraid 😞

**Comment by dazinator** [comment]
Ok no problem.
