### ISSUE TITLE
Populate called twice on same container

### ISSUE THREAD

**Issue by dazinator** [structuremap/StructureMap.Microsoft.DependencyInjection#34]
I am building a library to enable multi-tenancy applications, with tenant isolation and optionally module isolation.

This means there is a main application container, then a child container (per tenant), then optionally you can have `isolated` modules (which are child containers from the tenant container), or have some modules that aren't isolated, and directly add configuration to the `tenant` container.

At the moment, the order of play is Application Container is configured, then Tenant Container is created (and populated). Then if using Modules, Modules are located, and either child container is created for the module (isolated), or the existing tenant container is found and the module populates the tenant container (non isolated)

In order to keep my API's all container agnostic, all container configuration is using `IServiceCollection`. I am plugging in structure map as the default container provider as it supports nesting and child containers.

At the moment, for the non-isolated modules, I get an exception saying `Populate` can only be called once on a container. This happens because:

1. Tenant Container is populated via IServiceCollection
2. Modules are located, and each non-isolated module calls Populate() on the tenants container.

I could possibly give all non-isolated modules a single IServiceCollection but this would still result in Populate being called twice on the Tenant Container (once at the Tenant configuration level, and once at the module level for all of non-isolated modules that are loaded).

I could try to redesign my API's such that during tenant configuration, all non isolated modules are resolved at that point, so they can add services prior to the single `Populate` call, but this involves a tonne of redesign on my part - as this is all configured with a fluent API and I have designed the `Modules` section of the fluent API to be an `Add-On` rather than in-built into the tenant configuration API.

Is there any way you can make the constraint (i.e populate only being allowed to be called once) overridable - so I can disable it if I know I will be incrementally populating the container in stages?

**Comment by dazinator** [comment]
Thanks, much appreciated

**Comment by khellang** [comment]
:smile:
