### ISSUE TITLE
How Can This Be Used with a Windows Service

### ISSUE THREAD

**Issue by jkruer01** [structuremap/StructureMap.Microsoft.DependencyInjection#39]
Can this Nuget Package be used with a Windows Service?

If so, what is the proper use?

The windows service does a polling pass once every hour.  Each polling pass I want to create a nested container and then dispose of everything that was created within that polling pass.

Thank you!

**Comment by khellang** [comment]
The usage would be the same [as shown in the readme](https://github.com/structuremap/StructureMap.Microsoft.DependencyInjection#example-1). You'd just have to create the `IServiceCollection` yourself. You can do that by installing `Microsoft.Extensions.DependencyInjection` and new'in up a `ServiceCollection`.

**Comment by jkruer01** [comment]
Great! Thank you! That is what I am doing I just wanted to make sure that was the correct way to do it. Thanks!
