### ISSUE TITLE
Update to StructureMap 4.6.0

### ISSUE THREAD

**Issue by whizkidwwe1217** [structuremap/StructureMap.Microsoft.DependencyInjection#41]
Please support StructureMap 4.6.0

**Comment by khellang** [comment]
Want to send a pull request? 👼

**Comment by khellang** [comment]
BTW, what's the reason you can't just update to StructureMap 4.6.0 in your own application? Is it incompatible?

**Comment by whizkidwwe1217** [comment]
@khellang Sorry for the late reply. It's almost a year already :) I figured out my issue already. I just used the wrong version. Thanks! Closing this ticket.
