### ISSUE TITLE
Question : ASP.NET Core configuring StuructureMap container to Per Request 

### ISSUE THREAD

**Issue by masterarun** [structuremap/StructureMap.Microsoft.DependencyInjection#44]
Can someone clarify this below approach is correct.

I have configured Stucturemap in ConfigureServices as described.

1. Push the .net Core Services Collection into StructureMap
2. Return the service provider

Now I need to make Structuremap container to use nested container per request.

I was trying to override HttpContext RequestedService in ASP.NET Core Middleware with nested container like below.

```
public async Task Invoke(HttpContext httpContext)
 {
     using (var nestedContainer = Bootstrapper.Container.GetNestedContainer())
     {
          httpContext.RequestServices = nestedContainer.GetInstance<IServiceProvider>();
          await requestDelegate(httpContext);
     }
}
```

Is this the right approach?

Thanks.

**Comment by khellang** [comment]
ASP.NET Core already does this for you. That's why you have `RequestServices`.

**Comment by masterarun** [comment]
Thanks for you response.

So by default it will create nested container per request and will be disposed after.

**Comment by khellang** [comment]
Yup 👍🏻
